### PR TITLE
Extend python versions

### PR DESCRIPTION
**Pull request by gabor-boros**
## Description
Based on the comment of Pedro Garcia (https://spectrum.chat/thread/2e784cd4-e43f-40a4-87dc-7737ca38a63b?m=MTUzMjY4MjE0ODk0Mw==), I'm extending testing environments.

### CODE REVIEW

**Comment by gabor-boros** [comment]
It seems that Travis only supports 3.7-dev. Let's wait for the non dev version.

**Comment by grandquista** [comment]
Noted. I will keep an eye out for the change on their side.

**Comment by grandquista** [comment]
See the upstream issue travis-ci/travis-ci#9815

**Comment by gabor-boros** [comment]
@grandquista, it seems that we will have to use this workaround https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905

**Comment by gabor-boros** [comment]
PR51 is merged

**Pull request closed without merging**
