### PR TITLE
Add upload script with test URL.

### PR DESCRIPTION
**Pull request by grandquista**
The idea here is to upload releases from mater with increasing versions based on the last tagged feature release.

### CODE REVIEW

**Comment by grandquista** [comment]
Well that was a pointless 10 minute fix.

**Comment by grandquista** [comment]
Now just to get credentials from the old project.

**Comment by grandquista** [comment]
Agreed.

**Comment by gabor-boros** [comment]
@grandquista, Can I take this over?

**Comment by gabor-boros** [comment]
PyPi support has been contacted. Waiting for their reply. The issue is https://github.com/pypa/warehouse/issues/5284.

**Pull request merged**
