### PR TITLE
Update setup for release supporting python >= 3.5

### PR DESCRIPTION
**Pull request by lsabi**
**Reason for the change**
Update the setup for building the package

**Description**
A clear and concise description of what did you changed and why.

**Code examples**
If applicable, add code examples to help explain your changes.

**Checklist**
- [x] I have read and agreed to the [RethinkDB Contributor License Agreement](http://rethinkdb.com/community/cla/)

**References**
Anything else related to the change e.g. documentations, RFCs, etc.

### CODE REVIEW

**Comment by srh** [comment]
Why have this change?

**Comment by lsabi** [comment]
The changes are for python 3.5. Furthermore, maintaining python 2.x support while supporting python 3.5 and 3.10+ is complicated.

Do you think python 2.x should still be supported?

**Comment by srh** [comment]
Well, right now, the master branch works with Python 2.7.  So I don't think we should change the setup.py to disallow Python 2.7.

Also, Python 3.4 should still work, except for asyncio.

As for the future -- your lsabi/commands branch obviously has static types, which would make it impossibly annoying to maintain Python 2.

**Comment by lsabi** [comment]
Then it should be changed only to python `2.7` and `>=3.5` ?

For the future, I would drop even python `<3.6` support, as this has been as noted on the official website [https://devguide.python.org/versions/](https://devguide.python.org/versions/)

**Comment by srh** [comment]
I don't know enough about Python packaging to know whether adding `!=3.4.*` is a good idea or not; obviously asyncio stopped working so maybe we want it; I personally would pick whatever is least annoying to users in general but I'm not in charge of this project...

**Comment by lsabi** [comment]
Neither am I in charge, but I believe that most of the users will use python 3.6 or above, since major cloud providers have already dropped support (see list below). The best is to support the currently supported version and optionally 1-2 versions back.

[https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/](https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/)
[https://azure.microsoft.com/en-us/updates/azure-functions-support-for-python-36-is-ending-on-30-september-2022/](https://azure.microsoft.com/en-us/updates/azure-functions-support-for-python-36-is-ending-on-30-september-2022/)

**Pull request closed without merging**
