### PR TITLE
Fix for Issue No : #237

### PR DESCRIPTION
**Pull request by murali-shankar**
This is the fix for connection pool error.

**Reason for the change**
If applicable, link the related issue/bug report or write down in few sentences the motivation.

**Description**
A clear and concise description of what did you changed and why.

**Code examples**
If applicable, add code examples to help explain your changes.

**Checklist**
- [ ] I have read and agreed to the [RethinkDB Contributor License Agreement](http://rethinkdb.com/community/cla/)

**References**
Anything else related to the change e.g. documentations, RFCs, etc.

### CODE REVIEW

**Comment by McSinyx** [comment]
@gabor-boros, could you please take a look at this?

**Comment by gabor-boros** [comment]
@McSinyx I'll do that today and if everything seems to work fine, I'll include this to the next release

**Comment by gabor-boros** [comment]
@murali-shankar Thank you for your contribution! 👍  🎉

**Review by gabor-boros — APPROVED** [review]

**Comment by gabor-boros** [comment]
closes #237

**Pull request merged**
