### PR TITLE
fix tornado 5.0 with_timeout error

### PR DESCRIPTION
**Pull request by codeskyblue**
fix compatible with tornado 5.*

Same as https://github.com/rethinkdb/rethinkdb/pull/6654

Already tested with tornado 4.5.*, will not broke for it.

### CODE REVIEW

**Comment by codeskyblue** [comment]
On tornado 4.5 if not specified io_loop. io_loop will be set to IOLoop.current()

Code from <https://www.tornadoweb.org/en/branch4.5/_modules/tornado/gen.html>

```
def with_timeout(timeout, future, io_loop=None, quiet_exceptions=()):
    """Wraps a `.Future` (or other yieldable object) in a timeout.

    Raises `TimeoutError` if the input future does not complete before
    ``timeout``, which may be specified in any form allowed by
    `.IOLoop.add_timeout` (i.e. a `datetime.timedelta` or an absolute time
    relative to `.IOLoop.time`)

    If the wrapped `.Future` fails after it has timed out, the exception
    will be logged unless it is of a type contained in ``quiet_exceptions``
    (which may be an exception type or a sequence of types).

    Does not support `YieldPoint` subclasses.

    .. versionadded:: 4.0

    .. versionchanged:: 4.1
       Added the ``quiet_exceptions`` argument and the logging of unhandled
       exceptions.

    .. versionchanged:: 4.4
       Added support for yieldable objects other than `.Future`.
    """
    # TODO: allow YieldPoints in addition to other yieldables?
    # Tricky to do with stack_context semantics.
    #
    # It's tempting to optimize this by cancelling the input future on timeout
    # instead of creating a new one, but A) we can't know if we are the only
    # one waiting on the input future, so cancelling it might disrupt other
    # callers and B) concurrent futures can only be cancelled while they are
    # in the queue, so cancellation cannot reliably bound our waiting time.
    future = convert_yielded(future)
    result = Future()
    chain_future(future, result)
    if io_loop is None:
        io_loop = IOLoop.current()
```

**Comment by gabor-boros** [comment]
@codeskyblue this is awesome! Could you please add some test as well?

**Comment by codeskyblue** [comment]
Sure

**Comment by gabor-boros** [comment]
@codeskyblue thank you so much

**Comment by codeskyblue** [comment]
ping

**Comment by codeskyblue** [comment]
need this future very much, hope can merge soon

**Comment by gabor-boros** [comment]
@codeskyblue I’ll check it in some hours

**Comment by gabor-boros** [comment]
@codeskyblue Sorry for not mentioning before, shame on me, but this is how we addressed the "issue" of creating a new requirements file. What do you think about the solution mentioned here? https://github.com/rethinkdb/rethinkdb-python/pull/105

If you feel it would be much for this PR I totally understand, and I would do the adjustment later, when this PR is merged.

**Comment by codeskyblue** [comment]
It seems there is no need to create a new requirements file, Yes you can adjust this code, I can only have time tonight (tzzone +8:00)

**Pull request merged**
