### PR TITLE
Python 2 to 3

### PR DESCRIPTION
**Pull request by gabor-boros**
**Reason for the change**
https://github.com/rethinkdb/rethinkdb-python/issues/168

**Description**
Make the code Python 3.6+ compatible (and drop python2 support)

### CODE REVIEW

**Comment by gabor-boros** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 189
- Added 118
           

Coverage increased per file
===========================
+ rethinkdb/tornado_net/net_tornado.py  1
+ rethinkdb/errors.py  1
         

Coverage decreased per file
===========================
- rethinkdb/_dump.py  -1
- rethinkdb/net.py  -1
- rethinkdb/_export.py  -1
- rethinkdb/_index_rebuild.py  -1
         

Clones added
============
- rethinkdb/asyncio_net/net_asyncio.py  1
- rethinkdb/_dump.py  1
- rethinkdb/_export.py  1
- rethinkdb/trio_net/net_trio.py  1
- rethinkdb/ast.py  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/RethinkDB/rethinkdb-python/pullRequest?prid=5200254&bid=17054521)

**Comment by ShadowJonathan** [comment]
wait, the package was not python3-ready?

why was that not excluded in the `setup.py` file with `python_requires`?

**Comment by ShadowJonathan** [comment]
@gabor-boros could you change `python_requires=">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*",` in `setup.py` simply to `python_requires=">=3.6"`?

**Comment by gabor-boros** [comment]
@ShadowJonathan The package is already python 3 compatible. This PR is about to make it Python 3 only. Whenever the PR is in that state, I'll make sure that setup.py has the right required python version.

**Pull request closed without merging**
