### PR TITLE
Add trio test

### PR DESCRIPTION
**Pull request by mehaase**
Fixing Trio driver and adding a regression test.

### CODE REVIEW

**Comment by mehaase** [comment]
Hmm, the tests are failing on python 2.7 and 3.4. I've marked the Trio test to only run on Python ≥3.6, but `trio` is listed in `requirements.txt` and it does not have a package for older Pythons.

I'm not sure how to fix this. Should there be separate `requirements.txt` for different versions of Python?

**Comment by gabor-boros** [comment]
@mehaase it is a good question. I will try to look around how others do things like this. I would say that what you suggested could work but on the long run it will produce weird requirement files.

It would be great to have option to install dependency based on python versions. I’m pretty sure that there is an existing solution.

**Comment by gabor-boros** [comment]
@mehaase @grandquista I found the proper way to do conditional install. [PEP 508](https://www.python.org/dev/peps/pep-0508/) extends pip with this exact behavior. 

Due to `setup.py` will **not** install requirements from requirements.txt but from setup.py definition we could add trio to requirements file, however we could differentiate between test and non-test requirements.

In my opinion we could have a requirements.txt and requirements-test.txt in the repo and install both during testing on Travis.

What do you think guys?

**Comment by mehaase** [comment]
This is more problematic than I originally thought. The test does `import trio`, which won't work if Trio isn't installed, of course. Even if PEP-508 is a clean way to specify dependencies not to install in the Python 2.7 environment, the test runner will fail if it can't import that module.

> In my opinion we could have a requirements.txt and requirements-test.txt in the repo and install both during testing on Travis.

This is a good idea but it might need to be more fine-grained, i.e. `requirements-python3.txt`, because of the problem I mentioned above.

P.S. [Python 3.4 is EOL](https://devguide.python.org/#status-of-python-branches) as of 2 days ago. Should it be removed from the build matrix?

**Comment by gabor-boros** [comment]
What about excluding tests in the conftest file? In that case there is no python dependent requirements file needed (tests/conftest.py)

**Comment by grandquista** [comment]
https://github.com/rethinkdb/rethinkdb-python/blob/master/setup.py#L23-L28 is how the `requirements.txt` problem was fixed in the past.

https://github.com/rethinkdb/rethinkdb-python/blob/master/tests/conftest.py#L4-L7 is how the tests handle limitations in Python versions.

**Comment by grandquista** [comment]
> P.S. Python 3.4 is EOL as of 2 days ago. Should it be removed from the build matrix?

I have no opposition

**Comment by gabor-boros** [comment]
@mehaase hello, what’s the status of this PR?

**Comment by mehaase** [comment]
Sorry this slipped my mind. I will address it today.

**Pull request merged**
